export interface Product {
  id: number;
  name: string;
  brand: string;
  model: string;
  engineCode: string;
  oemNumber: string;
  price: number;
  b2bPrice: number;
  warranty: string;
  available: boolean;
  isNew: boolean;
  isBestseller: boolean;
  description: string;
  specs: string[];
}

export interface Category {
  name: string;
  slug: string;
  count: number;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Turbosprężarka regenerowana Garrett GTC1549MVZ 2.0 TDI Nr kat. Garrett: 785448-5005S",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "",
    oemNumber: "03L253010F",
    price: 909,
    b2bPrice: 800,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 2,
    name: "Turbosprężarka GARRETT 850840 do Ford Transit 2.0 EcoBlue  Turbo Ford Transit Tourneo 2.0 ",
    brand: "Ford",
    model: "Transit",
    engineCode: "",
    oemNumber: "850840",
    price: 1099,
    b2bPrice: 970,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Ford Transit. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 3,
    name: "Turbosprężarka GARRETT 874595 - Audi A4 B9 / A5 F5 2.0 TFSI Fabrycznie nowa | OEM | Mild H",
    brand: "Audi",
    model: "A4 B9 / A5 F5",
    engineCode: "",
    oemNumber: "874595",
    price: 1799,
    b2bPrice: 1580,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Fabrycznie nowa turbosprężarka Garrett 874595 do Audi A4 B9 i A5 F5 2.0 TFSI (150–190 KM).\nOEM: 06N145701D. Mild Hybrid. Plug &amp; Play – gotowa do montażu.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 4,
    name: "Turbosprężarka GARRETT 04L253022B - VW Transporter T6 / Multivan / Crafter / MAN TGE 2.0 T",
    brand: "Volkswagen",
    model: "Transporter",
    engineCode: "",
    oemNumber: "04L253022B",
    price: 1509,
    b2bPrice: 1330,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka GARRETT 04L253022B do silników 2.0 TDI.Regeneracja na TurboTechnics VSR301, kalibracja przepływu G3-Min-Flow, NOWY rdzeń CHRA, komplet nowych uszczelek.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 5,
    name: "Turbosprężarka Garrett 838452 Ford Transit 2.0 TDCi EcoBlue MK8 RWD 105KM 130KM 170KM | Re",
    brand: "Ford",
    model: "Transit",
    engineCode: "",
    oemNumber: "838452",
    price: 1099,
    b2bPrice: 970,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Garrett 838452 do Ford Transit 2.0 TDCi EcoBlue MK8 RWD (105/130/170 KM, od 2016). Regeneracja na TurboTechnics VSR301, ustawianie przepływu G3-Min-Flow (G3 ",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 6,
    name: "Turbosprężarka Garrett 852072 Ford 2.0 TDCi EcoBlue - Regenerowana | Nowy rdzeń CHRA",
    brand: "Ford",
    model: "2.0 TDCi",
    engineCode: "",
    oemNumber: "852072",
    price: 1099,
    b2bPrice: 970,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Garrett 852072 do silników Ford 2.0 TDCi EcoBlue (1995 cm³): 120/150/190 KM. Regeneracja na TurboTechnics VSR301, ustawienie przepływu G3-Min-Flow (G3 Concep",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 7,
    name: "Turbosprężarka 49335 2.0D N47D20 N47D20C N47TUE BMW 320D 520D X3 163 184KM",
    brand: "BMW",
    model: "320D 520D X3 163 184KM",
    engineCode: "N47D20 / N47D20C",
    oemNumber: "18471697681",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka BMW 320D 520D X3 163 184KM. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 8,
    name: "Turbosprężarka BMW 320D 520D 420D 220D 120D X3 X1 2.0D N47D20 163KM 184KM",
    brand: "BMW",
    model: "320D 520D 420D 220D 120D X3 X1",
    engineCode: "N47D20",
    oemNumber: "18471697167",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka BMW 320D 520D 420D 220D 120D X3 X1. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 9,
    name: "Turbosprężarka N47D20 N47D20C 163KM 184KM BMW 120D 320D 520D X3 X1 uszczelk",
    brand: "BMW",
    model: "120D 320D 520D X3 X1 uszczelk",
    engineCode: "N47D20 / N47D20C",
    oemNumber: "18471695778",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka BMW 120D 320D 520D X3 X1 uszczelk. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 10,
    name: "Turbosprężarka BMW 120D 220D 320D 420D 520D X3 2.0D N47D20 163KM 184KM uszc",
    brand: "BMW",
    model: "120D 220D 320D 420D 520D X3",
    engineCode: "N47D20",
    oemNumber: "18471671615",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka BMW 120D 220D 320D 420D 520D X3. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 11,
    name: "Turbosprężarka 53039700137 BV43 2.0 TDI CEGA CBBB 170KM VW Golf Passat Audi",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "BV43",
    oemNumber: "18471668200",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 12,
    name: "Turbosprężarka VW Golf Passat Tiguan Audi A3 TT Seat Skoda 2.0 TDI CEGA 170",
    brand: "Audi",
    model: "A3 TT Seat Skoda",
    engineCode: "",
    oemNumber: "18471663753",
    price: 1349,
    b2bPrice: 1190,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi A3 TT Seat Skoda. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 13,
    name: "Turbosprężarka 2.0 TDI CEGA CBBB 170KM VW Golf Passat Tiguan Audi A3 BV43",
    brand: "Audi",
    model: "A3 BV43",
    engineCode: "BV43",
    oemNumber: "18471662690",
    price: 1449,
    b2bPrice: 1280,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi A3 BV43. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 14,
    name: "Turbosprężarka 2.0 TDI CEGA CBBB 170KM Audi VW Golf Passat Tiguan BV43",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "BV43",
    oemNumber: "18471634534",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 15,
    name: "Turbosprężarka 54409 BorgWarner VW Golf Passat Audi A4 2.0 TDI CFHA 140KM",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "",
    oemNumber: "18471632790",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 16,
    name: "Turbosprężarka VW Golf Passat Audi A4 A3 Seat Skoda 2.0 TDI CFHA CFHB 140KM",
    brand: "Audi",
    model: "A4 A3 Seat Skoda",
    engineCode: "",
    oemNumber: "18471632404",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi A4 A3 Seat Skoda. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 17,
    name: "Turbosprężarka 2.0 TDI CFHA CFHB CLCA 140KM Audi VW Golf Passat Skoda Seat",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "",
    oemNumber: "18471624344",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 18,
    name: "Turbosprężarka BorgWarner Audi VW Seat Skoda 2.0 TDI 140KM CFHA 03L253056G",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "",
    oemNumber: "03L253056G",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 19,
    name: "Turbosprężarka Opel Insignia Zafira C Cascada 2.0 CDTI B20DTH 844572 170KM",
    brand: "Opel",
    model: "Insignia Zafira C Cascada",
    engineCode: "B20DTH",
    oemNumber: "18463259322",
    price: 1799,
    b2bPrice: 1580,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel Insignia Zafira C Cascada. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 20,
    name: "Turbosprężarka Garrett BMW 120D 320D 520D X3 2.0D B47D20 190KM 819976+USZCZ",
    brand: "BMW",
    model: "120D 320D 520D X3",
    engineCode: "B47D20",
    oemNumber: "18463158335",
    price: 1699,
    b2bPrice: 1500,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka BMW 120D 320D 520D X3. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 21,
    name: "Turbosprężarka Garrett VW Golf 7 Audi A3 Seat 1.6TDI CLHA 813860 90 105 110",
    brand: "Audi",
    model: "A3 Seat",
    engineCode: "",
    oemNumber: "18463065099",
    price: 1099,
    b2bPrice: 970,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi A3 Seat. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 22,
    name: "Turbosprężarka BiTurbo VW 2.0 BiTDI 53049700139 K04 T5 T6 Amarok CFCA",
    brand: "Volkswagen",
    model: "Volkswagen turbo",
    engineCode: "K04",
    oemNumber: "18448261265",
    price: 2999,
    b2bPrice: 2640,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 23,
    name: "Turbosprężarka regenerowana BiTurbo VW T5 T6 Amarok 2.0 BiTDI K04 CFCA",
    brand: "Volkswagen",
    model: "Volkswagen turbo",
    engineCode: "K04",
    oemNumber: "18448259690",
    price: 2999,
    b2bPrice: 2640,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 24,
    name: "Turbosprężarka BiTurbo VW Transporter T5 T6 Amarok 2.0 BiTDI CFCA 180KM",
    brand: "Volkswagen",
    model: "Transporter",
    engineCode: "",
    oemNumber: "18448205744",
    price: 2999,
    b2bPrice: 2640,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen Transporter. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 25,
    name: "Turbosprężarka BiTurbo Mazda 3 6 CX-5 CX-7 2.2D 150 175KM SHY8 SH01",
    brand: "Inne",
    model: "Inne turbo",
    engineCode: "SH01",
    oemNumber: "18448068039",
    price: 1699,
    b2bPrice: 1500,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Inne . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 26,
    name: "Turbosprężarka 2.0 TDI 143KM Audi A4 B8 A5 Q5 Exeo CGLC CJCA + USZCZELKI",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "",
    oemNumber: "18421966015",
    price: 999,
    b2bPrice: 880,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 27,
    name: "TURBOSPRĘŻARKA FORD KUGA PEUGEOT 3008 2.0 TDCI DW10FC 53039880265 150 177KM",
    brand: "Ford",
    model: "KUGA PEUGEOT 3008",
    engineCode: "",
    oemNumber: "18402165822",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford KUGA PEUGEOT 3008. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 28,
    name: "REGENEROWANE TURBO PEUGEOT 508 FORD MONDEO 2.0 BLUEHDI TDCI 53039880394",
    brand: "Ford",
    model: "MONDEO",
    engineCode: "",
    oemNumber: "18402155871",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford MONDEO. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 29,
    name: "TURBO FORD TRANSIT CONNECT 1.0 ECOBOOST 3ZYL 125 140 KM 1808411 USZCZELKI",
    brand: "Ford",
    model: "TRANSIT CONNECT",
    engineCode: "",
    oemNumber: "18402148626",
    price: 949,
    b2bPrice: 840,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford TRANSIT CONNECT. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 30,
    name: "REGENEROWANE TURBO FORD FOCUS FIESTA 1.0 ECOBOOST CM5G6K682GB 125KM 140KM",
    brand: "Ford",
    model: "FOCUS FIESTA",
    engineCode: "",
    oemNumber: "18402145611",
    price: 899,
    b2bPrice: 790,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford FOCUS FIESTA. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 31,
    name: "REGENEROWANE TURBO FORD FOCUS FIESTA 1.0 ECOBOOST CM5G6K682GB 125KM 140KM",
    brand: "Ford",
    model: "FOCUS FIESTA",
    engineCode: "",
    oemNumber: "18402119465",
    price: 919,
    b2bPrice: 810,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford FOCUS FIESTA. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 32,
    name: "TURBO 1.5 BLUEHDI PEUGEOT RIFTER CITROEN BERLINGO 853603 1631887180 USZCZEL",
    brand: "Opel",
    model: "Opel turbo",
    engineCode: "",
    oemNumber: "18402112222",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 33,
    name: "TURBOSPRĘŻARKA OPEL VIVARO TOYOTA PROACE 1.5 DIESEL 853603 DV5RC USZCZELKI",
    brand: "Opel",
    model: "VIVARO TOYOTA PROACE",
    engineCode: "",
    oemNumber: "18402111066",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel VIVARO TOYOTA PROACE. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 34,
    name: "REGENEROWANE TURBO PEUGEOT 3008 CITROEN 1.5 BLUEHDI 853603 9820728080 130KM",
    brand: "Opel",
    model: "Opel turbo",
    engineCode: "",
    oemNumber: "18402110143",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 35,
    name: "TURBOSPRĘŻARKA 5438-970-0003 5438-970-0009 5438-970-0011 5438-970-0013",
    brand: "Opel",
    model: "Opel turbo",
    engineCode: "",
    oemNumber: "18402095460",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 36,
    name: "TURBOSPRĘŻARKA 1.6CDTI OPEL ASTRA INSIGNIA ZAFIRA 94 109 136KM 54389700013",
    brand: "Opel",
    model: "ASTRA INSIGNIA ZAFIRA 94 109 1",
    engineCode: "",
    oemNumber: "18402092412",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel ASTRA INSIGNIA ZAFIRA 94 109 1. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 37,
    name: "TURBOSPRĘŻARKA IHI MAZDA 6 GY GG 2.0 DI RF5C VJ32 RF5C13.700 + USZCZELKI",
    brand: "Inne",
    model: "Inne turbo",
    engineCode: "VJ32",
    oemNumber: "18383002998",
    price: 799,
    b2bPrice: 700,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Inne . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 38,
    name: "TURBO HYUNDAI TUCSON KIA SPORTAGE 1.6 CRDI 843814-5008S 28231-2U000 D4FE",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "",
    oemNumber: "18383001761",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Hyundai . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 39,
    name: "TURBOSPRĘŻARKA KIA CEED STONIC HYUNDAI I30 1.6 CRDI D4FE 16359700028 136KM",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "I30",
    oemNumber: "18383000605",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Hyundai . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 40,
    name: "REGENEROWANE TURBO KIA SPORTAGE HYUNDAI TUCSON 1.6CRDI 843814 282312U000",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "",
    oemNumber: "18382988386",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Hyundai . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 41,
    name: "TURBOSPRĘŻARKA RENAULT ESPACE KOLEOS 2.0 DCI 49180-19700 144105414R 200KM",
    brand: "Renault",
    model: "ESPACE KOLEOS",
    engineCode: "",
    oemNumber: "18382979529",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Renault ESPACE KOLEOS. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 42,
    name: "REGENEROWANE TURBO RENAULT TRAFIC 2.0 DCI M9R 49131-07430 144105051R 170KM",
    brand: "Renault",
    model: "TRAFIC",
    engineCode: "",
    oemNumber: "18382976387",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Renault TRAFIC. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 43,
    name: "TURBO VOLKSWAGEN CRAFTER 2.0 TDI 102KM 140KM 04L253014F 873970-5001S USZCZE",
    brand: "Volkswagen",
    model: "CRAFTER",
    engineCode: "",
    oemNumber: "04L253014F",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen CRAFTER. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 44,
    name: "TURBOSPRĘŻARKA VW CRAFTER 2.0 TDI BMT 873970 845888 04L253056R USZCZELKI",
    brand: "Volkswagen",
    model: "CRAFTER",
    engineCode: "",
    oemNumber: "04L253056R",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen CRAFTER. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 45,
    name: "TURBOSPRĘŻARKA VW CRAFTER 2.0 TDI DAUA DAUB 873970 04L253014F 140KM USZCZEL",
    brand: "Volkswagen",
    model: "CRAFTER",
    engineCode: "",
    oemNumber: "04L253014F",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen CRAFTER. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 46,
    name: "TURBO MERCEDES V-KLASA W447 SPRINTER 2.0 OM654 873798 911025 USZCZELKI",
    brand: "Mercedes",
    model: "Mercedes turbo",
    engineCode: "W447 / OM654",
    oemNumber: "18376334443",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Mercedes . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 47,
    name: "TURBOSPRĘŻARKA MERCEDES SPRINTER 317 CDI W447 873798 6540905000 170KM",
    brand: "Mercedes",
    model: "SPRINTER 317 CDI W447 873798 6",
    engineCode: "W447",
    oemNumber: "18376333704",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Mercedes SPRINTER 317 CDI W447 873798 6. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 48,
    name: "REGENEROWANE TURBO MERCEDES V220 W447 SPRINTER 2.0 873798 A6540905000",
    brand: "Mercedes",
    model: "V220 W447 SPRINTER",
    engineCode: "V220 / W447",
    oemNumber: "A6540905000",
    price: 1599,
    b2bPrice: 1410,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Mercedes V220 W447 SPRINTER. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 49,
    name: "TURBOSPRĘŻARKA VW POLO GTI S1 TT 1.8 DAJB CJXC IHI 06K145702Q + USZCZELKI",
    brand: "Audi",
    model: "Audi turbo",
    engineCode: "",
    oemNumber: "06K145702Q",
    price: 1299,
    b2bPrice: 1140,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 50,
    name: "Turbosprężarka 06K145701T IHI 1.8 / 2.0 TSI TFSI Audi VW Skoda Seat",
    brand: "Audi",
    model: "Audi turbo",
    engineCode: "",
    oemNumber: "06K145701T",
    price: 1299,
    b2bPrice: 1140,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Turbosprężarka 06K145701T IHI do 1.8 / 2.0 TSI TFSI Audi, VW, Skoda i Seat. Nowy CHRA, wyważanie TurboTechnics VSR400, kalibracja G3-MIN-FLOW i G3-REA-MASTER, komplet uszczelek, 24 miesiące gwarancji.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 51,
    name: "TURBO IHI VW GOLF VII GTI AUDI A3 2.0 TFSI 06K145702Q 06K145722H 230KM",
    brand: "Audi",
    model: "2.0 TFSI",
    engineCode: "",
    oemNumber: "06K145702Q",
    price: 1299,
    b2bPrice: 1140,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TFSI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 52,
    name: "TURBOSPRĘŻARKA AUDI A3 Q3 PASSAT B8 2.0 TDI 04L253010B BM70B + USZCZELKI",
    brand: "Audi",
    model: "A3 Q3 PASSAT B8",
    engineCode: "BM70B",
    oemNumber: "04L253010B",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi A3 Q3 PASSAT B8. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 53,
    name: "TURBOSPRĘŻARKA AUDI Q3 SKODA OCTAVIA 2.0 35TDI 150KM 05L253019FX 05L253019F",
    brand: "Audi",
    model: "Audi turbo",
    engineCode: "",
    oemNumber: "05L253019F",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 54,
    name: "Turbosprężarka 776470 / 059145722M 3.0 TDI Audi A6 Q7 Touareg",
    brand: "Audi",
    model: "A6 Q7 Touareg",
    engineCode: "",
    oemNumber: "18376201766",
    price: 1149,
    b2bPrice: 1010,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Turbosprężarka 776470 3.0 TDI Audi A6 Q7 Touareg | TURBO-GIT",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 55,
    name: "TURBO RENAULT KADJAR NISSAN QASHQAI 1.7 DCI 144108640R 49180-04310 R9N VITO",
    brand: "Mercedes",
    model: "Mercedes turbo",
    engineCode: "",
    oemNumber: "18375898119",
    price: 1249,
    b2bPrice: 1100,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Mercedes . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 56,
    name: "TURBOSPRĘŻARKA VW T6 MULTIVAN 2.0TDI 830324 CXGB 102 84KM CXGA CAAA+USZCZEL",
    brand: "Volkswagen",
    model: "MULTIVAN",
    engineCode: "",
    oemNumber: "18375749512",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen MULTIVAN. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 57,
    name: "Turbosprężarka MITSUBISHI L200 PAJERO SPORT 2.4 DI-D 4N15 49335-01702",
    brand: "Inne",
    model: "Inne turbo",
    engineCode: "L200",
    oemNumber: "18375567712",
    price: 1229,
    b2bPrice: 1080,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Inne . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 58,
    name: "TURBOSPRĘŻARKA 786880 FORD TRANSIT MK8 2.2TDCI 155KM BK2Q-6K682-CA uszczelk",
    brand: "Ford",
    model: "TRANSIT MK8",
    engineCode: "",
    oemNumber: "18375534443",
    price: 1049,
    b2bPrice: 920,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford TRANSIT MK8. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 59,
    name: "TURBOSPRĘŻARKA GARRETT 814698 OPEL ASTRA J / K 1.6 CDTI 110 KM 136 KM",
    brand: "Opel",
    model: "1.6 CDTI",
    engineCode: "",
    oemNumber: "814698",
    price: 999,
    b2bPrice: 880,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Opel 1.6 CDTI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 60,
    name: "TURBOSPRĘŻARKA 1.5 BLUEHDI PEUGEOT CITROEN OPEL TOYOTA 102 120 128KM NOWY",
    brand: "Opel",
    model: "TOYOTA 102 120 128KM NOWY",
    engineCode: "",
    oemNumber: "18373053710",
    price: 1449,
    b2bPrice: 1280,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel TOYOTA 102 120 128KM NOWY. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 61,
    name: "Turbosprężarka 54389700006 1.5 dCi / CDI Renault Dacia Nissan Mercedes",
    brand: "Mercedes",
    model: "1.5 dCi",
    engineCode: "",
    oemNumber: "18373037482",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Turbosprężarka 54389700006 1.5 dCi / CDI Renault Dacia Nissan Mercedes | TURBO-GIT",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 62,
    name: "TURBO FORD TOURNEO CUSTOM 2.0ECOBLUE 105 KM 838417 130 170",
    brand: "Ford",
    model: "TOURNEO CUSTOM",
    engineCode: "",
    oemNumber: "18373017120",
    price: 1349,
    b2bPrice: 1190,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford TOURNEO CUSTOM. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 63,
    name: "Turbosprężarka JAGUAR /LAND ROVER 2.0 D 180KM Discovery Sport Evoque XF XE",
    brand: "Inne",
    model: "Inne turbo",
    engineCode: "",
    oemNumber: "18372999267",
    price: 1299,
    b2bPrice: 1140,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Inne . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 64,
    name: "TURBOSPRĘŻARKA 1.6CDTI OPEL ASTRA INSIGNIA MOKKA ZAFIRA 94 109 136KM",
    brand: "Opel",
    model: "ASTRA INSIGNIA MOKKA ZAFIRA 94",
    engineCode: "",
    oemNumber: "18372984309",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Opel ASTRA INSIGNIA MOKKA ZAFIRA 94. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 65,
    name: "TURBOSPRĘŻARKA IHI VJ40 VJ41 MAZDA 3 / MAZDA 6 2.2 MZR-CD 125-185 KM",
    brand: "Inne",
    model: "Inne turbo",
    engineCode: "VJ40 / VJ41",
    oemNumber: "18372877669",
    price: 1149,
    b2bPrice: 1010,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Inne . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 66,
    name: "TURBOSPRĘŻARKA 54389700005 54389700018 1.6dCi 136KM RENAULT NISSAN MERCEDES",
    brand: "Mercedes",
    model: "1.6dCi",
    engineCode: "",
    oemNumber: "18372704736",
    price: 899,
    b2bPrice: 790,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Mercedes 1.6dCi. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 67,
    name: "TURBOSPRĘŻARKA 756047 PEUGEOT CITROEN 2.0HDI 136KM 307 308 407 508 C4 C5",
    brand: "Peugeot",
    model: "CITROEN",
    engineCode: "",
    oemNumber: "18372685666",
    price: 949,
    b2bPrice: 840,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Peugeot CITROEN. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 68,
    name: "TURBOSPRĘŻARKA 873767 VW CRAFTER T6 CARAVELLE MULTIVAN 2.0TDI 102 140 150",
    brand: "Volkswagen",
    model: "CRAFTER",
    engineCode: "",
    oemNumber: "18372660855",
    price: 1250,
    b2bPrice: 1100,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen CRAFTER. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 69,
    name: "TURBOSPRĘŻARKA GARRETT 715910 MERCEDES E270 CDI ML270 CDI OM612 163KM 170KM",
    brand: "Mercedes",
    model: "E270 CDI ML270 CDI OM612 163KM",
    engineCode: "E270 / ML270",
    oemNumber: "715910",
    price: 899,
    b2bPrice: 790,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Mercedes E270 CDI ML270 CDI OM612 163KM. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 70,
    name: "TURBOSPRĘŻARKA GARRETT 792290 VW TRANSPORTER T5 T6 2.0 TDI 102 140 KM CAAA",
    brand: "Volkswagen",
    model: "TRANSPORTER",
    engineCode: "",
    oemNumber: "792290",
    price: 1249,
    b2bPrice: 1100,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen TRANSPORTER. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 71,
    name: "Turbosprężarka Garrett 792290 VW Transporter T5 T6 2.0 TDI 84 KM CAAA",
    brand: "Volkswagen",
    model: "Transporter",
    engineCode: "",
    oemNumber: "792290",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen Transporter. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 72,
    name: "Turbosprężarka BiTurbo Volvo 2.0 D D4204T14 / D4204T5 D3 D4",
    brand: "Volvo",
    model: "2",
    engineCode: "D4204T14 / D4204T5",
    oemNumber: "18372573763",
    price: 2299,
    b2bPrice: 2020,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Turbosprężarka BiTurbo Volvo 2.0 D D4204T14 / D4204T5 | TURBO-GIT",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 73,
    name: "Turbosprężarka 06K145654K 2.0 TFSI 190-230KM VW Audi Q3 A3 A4 A5 USZCZELKI",
    brand: "Audi",
    model: "2.0 TFSI",
    engineCode: "",
    oemNumber: "06K145654K",
    price: 1650,
    b2bPrice: 1450,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TFSI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 74,
    name: "Turbosprężarka 834009 Subaru Forester Impreza Legacy 2.0D150KM EE20Z",
    brand: "Inne",
    model: "2.0D1",
    engineCode: "EE20Z",
    oemNumber: "18312823215",
    price: 1950,
    b2bPrice: 1720,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Inne 2.0D1. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 75,
    name: "TURBOSPRĘŻARKA 898906-0004 DUCATO BOXER JUMPER 2.2 HDI 120-165KM",
    brand: "Peugeot",
    model: "Peugeot turbo",
    engineCode: "",
    oemNumber: "18312812943",
    price: 1850,
    b2bPrice: 1630,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Peugeot . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 76,
    name: "TURBOSPRĘŻARKA 49335-01120 MITSUBISHI OUTLANDER 2.2 DI-D 150KM + USZCELKI",
    brand: "Inne",
    model: "Inne turbo",
    engineCode: "",
    oemNumber: "18292156147",
    price: 999,
    b2bPrice: 880,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Inne . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 77,
    name: "TURBOSPRĘŻARKA 49373-02000 1.4HDI 1.6 HDI CITROEN PEUGEOT FORD TDCi 90 95KM",
    brand: "Ford",
    model: "TDCi 90 95KM",
    engineCode: "",
    oemNumber: "18292105010",
    price: 899,
    b2bPrice: 790,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford TDCi 90 95KM. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 78,
    name: "Turbosprężarka 04L253010B 2.0TDI Audi VW Seat Skoda 102 150KM A3 A4 Golf 7",
    brand: "Audi",
    model: "2.0TDI",
    engineCode: "",
    oemNumber: "04L253010B",
    price: 1299,
    b2bPrice: 1140,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 79,
    name: "Turbosprężarka Garrett 831120 Mercedes E200 E220 W213 Vito 2.0CDI 163 192km",
    brand: "Mercedes",
    model: "E200 E220 W213 Vito",
    engineCode: "E200 / E220",
    oemNumber: "831120",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Mercedes E200 E220 W213 Vito. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 80,
    name: "Turbosprężarka Garrett 843814 Hyundai Kia 1.6 CRDi i30 Ceed Tucson+uszczelk",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "",
    oemNumber: "843814",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Hyundai . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 81,
    name: "Turbosprężarka Garrett 856652 839827 Hyundai Kia 1.0 T-GDI 100-120KM+uszcze",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "",
    oemNumber: "856652",
    price: 1699,
    b2bPrice: 1500,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Hyundai . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 82,
    name: "Turbosprężarka 2.0 BlueHDi TDCi HDi 150-177KM Ford Peugeot Citroen+uszczelk",
    brand: "Ford",
    model: "Ford turbo",
    engineCode: "",
    oemNumber: "18271052515",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 83,
    name: "Turbosprężarka Garrett 04L253022B VW T6 Crafter MAN TGE 2.0 TDI 110-150 KM",
    brand: "Volkswagen",
    model: "Crafter",
    engineCode: "",
    oemNumber: "04L253022B",
    price: 1799,
    b2bPrice: 1580,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Volkswagen Crafter. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 84,
    name: "Turbosprężarka 852072 Ford 2.0 TDCi EcoBlue 120-190KM Nowy CHRA+USZCZELKI",
    brand: "Ford",
    model: "2.0 TDCi",
    engineCode: "",
    oemNumber: "18269499090",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Ford 2.0 TDCi. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 85,
    name: "Turbosprężarka Garrett 838452 Ford Transit 2.0 EcoBlue 105 130 170 KM+USZCZ",
    brand: "Ford",
    model: "Transit",
    engineCode: "",
    oemNumber: "838452",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Ford Transit. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 86,
    name: "Turbosprężarka GARRETT 850840 Ford Transit 2.0D EcoBlue Tourneo 105 130 170",
    brand: "Ford",
    model: "Transit",
    engineCode: "",
    oemNumber: "850840",
    price: 1249,
    b2bPrice: 1100,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford Transit. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 87,
    name: "Turbosprężarka 49135-05895 BMW 120d 320d 520d X3 N47 177KM E91 E90 E92 E93",
    brand: "BMW",
    model: "120d 320d 520d X3 N47 177KM E9",
    engineCode: "N47 / E91",
    oemNumber: "18271048433",
    price: 999,
    b2bPrice: 880,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka BMW 120d 320d 520d X3 N47 177KM E9. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 88,
    name: "Turbosprężarka 49135-05895 BMW 120d 320d 520d X3 N47 177KM E91 E90 E92 E93",
    brand: "BMW",
    model: "120d 320d 520d X3 N47 177KM E9",
    engineCode: "N47 / E91",
    oemNumber: "18271011511",
    price: 979,
    b2bPrice: 860,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka BMW 120d 320d 520d X3 N47 177KM E9. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 89,
    name: "TURBOSPRĘŻARKA 53039700652 KIA SORENTO IV HYUNDAI SANTA FE 2.2 CRDI 200KM",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "",
    oemNumber: "18422088110",
    price: 1699,
    b2bPrice: 1500,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Hyundai . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 90,
    name: "Turbosprężarka 05L253019F VW Audi 2.0 TDI 150KM Passat Tiguan Golf Trock",
    brand: "Audi",
    model: "2.0 TDI",
    engineCode: "",
    oemNumber: "05L253019F",
    price: 1350,
    b2bPrice: 1190,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi 2.0 TDI. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 91,
    name: "TURBOSPRĘŻARKA 2.0 TSI TFSI VW AUDI SEAT 210KM 220KM 230KM 231KM 06K145702N",
    brand: "Audi",
    model: "Audi turbo",
    engineCode: "",
    oemNumber: "06K145702N",
    price: 1350,
    b2bPrice: 1190,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Audi . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 92,
    name: "TURBOSPRĘŻARKA FORD TRANSIT / RANGER 2.2 TDCi Garrett 787556 100 150 153km",
    brand: "Ford",
    model: "2.2 TDCi",
    engineCode: "",
    oemNumber: "787556",
    price: 1099,
    b2bPrice: 970,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford 2.2 TDCi. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 93,
    name: "TURBO OPEL VIVARO FIAT TALENTO 2.0 DCI 49131-07400 144107853R + USZCZELKI",
    brand: "Renault",
    model: "Renault turbo",
    engineCode: "",
    oemNumber: "18382981013",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Renault . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 94,
    name: "TURBOSPRĘŻARKA 2.0 DCI 16V ADBLUE RENAULT NISSAN FIAT 120-200KM TRAFIC",
    brand: "Renault",
    model: "Renault turbo",
    engineCode: "",
    oemNumber: "18292067430",
    price: 1399,
    b2bPrice: 1230,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Renault . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 95,
    name: "TURBOSPRĘŻARKA 49172-03000 1.5 1.6 HDI TDCI PEUGEOT CITROEN FORD 75 90 99km",
    brand: "Ford",
    model: "75 90 99km",
    engineCode: "",
    oemNumber: "18292034357",
    price: 829,
    b2bPrice: 730,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Ford 75 90 99km. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 96,
    name: "TURBOSPRĘŻARKA 781504 OPEL CHEVROLET 1.4 TURBO 120KM 140KM 150KM+uszczelki",
    brand: "Opel",
    model: "CHEVROLET",
    engineCode: "",
    oemNumber: "18274105485",
    price: 999,
    b2bPrice: 880,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Opel CHEVROLET. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 97,
    name: "TURBOSPRĘŻARKA re 822088 FIAT 1.3 JTD MULTIJET | DOBLO PANDA PUNTO CORSA 95KM",
    brand: "Inne",
    model: "Inne turbo",
    engineCode: "",
    oemNumber: "18274055668",
    price: 1299,
    b2bPrice: 1140,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: false,
    description: "Profesjonalnie regenerowana turbosprężarka Inne . Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 98,
    name: "Turbosprężarka Audi A4/A5 2.0 TFSI MHEV 150‑190 KM (OEM 06N145701D)",
    brand: "Audi",
    model: "A4/A5",
    engineCode: "",
    oemNumber: "06N145701D",
    price: 1999,
    b2bPrice: 1760,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi A4/A5. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 99,
    name: "Regenerowana turbosprężarka Audi A4/A5 2.0 TFSI 150‑190 KM (OEM 06N145701D) – gwarancja 24",
    brand: "Audi",
    model: "A4/A5",
    engineCode: "",
    oemNumber: "06N145701D",
    price: 1999,
    b2bPrice: 1760,
    warranty: "24 miesiące",
    available: true,
    isNew: true,
    isBestseller: true,
    description: "Profesjonalnie regenerowana turbosprężarka Audi A4/A5. Pełna regeneracja w standardzie VSR 301. Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 100,
    name: "Regenerowana turbosprężarka Hyundai KIA 2.0 CRDi 185KM",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "",
    oemNumber: "",
    price: 1999,
    b2bPrice: 1760,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: true,
    description: "Regenerowana turbosprężarka do aut Hyundai i KIA (iX35, Santa Fe, Sorento, Sportage) z silnikami 2.0 CRDi. Kody silnika: D4EAF, D4HA. 24 miesiące gwarancji.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 101,
    name: "Regenerowana turbosprężarka Audi VW Skoda 1.9 TDI 100KM AXR",
    brand: "Audi",
    model: "1.9 TDI",
    engineCode: "",
    oemNumber: "",
    price: 1199,
    b2bPrice: 1060,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: false,
    description: "Regenerowana turbina do aut Audi, VW, Skoda 1.9 TDI 100KM (Golf, Octavia, A3). Kody silnika: AXR, BEW, BSW.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 102,
    name: "Regenerowana turbosprężarka Citroen Peugeot 2.7 HDi V6 204KM",
    brand: "Peugeot",
    model: "Peugeot",
    engineCode: "",
    oemNumber: "",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: true,
    description: "Turbina dla Citroen C6, Peugeot 407 607 z silnikiem 2.7 HDi V6 204KM. Kod: DT17TED4.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 103,
    name: "Regenerowana turbosprężarka Mercedes 3.0 CDI V6 OM642",
    brand: "Mercedes",
    model: "Mercedes turbo",
    engineCode: "OM642",
    oemNumber: "",
    price: 1799,
    b2bPrice: 1580,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: true,
    description: "Turbina do Mercedes, Chrysler, Jeep 3.0 CDI (OM642) - ML320, GL320, E320, 300C.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 104,
    name: "Regenerowana turbosprężarka Volvo 2.4 D D5244T5 185KM",
    brand: "Volvo",
    model: "2",
    engineCode: "D5244T5",
    oemNumber: "",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: true,
    description: "Turbina do aut Volvo S40, S60, V50, V70, XC90 z silnikami 2.4 D (185KM).",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 105,
    name: "Regenerowana turbosprężarka Bi-Turbo Ford Mondeo S-Max 2.0 TDCi 210KM",
    brand: "Ford",
    model: "2.0 TDCi",
    engineCode: "",
    oemNumber: "",
    price: 2699,
    b2bPrice: 2380,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: true,
    description: "Turbina Bi-Turbo dla Ford Mondeo, S-Max, Edge, Galaxy 2.0 TDCi (210KM). Kody: T9CB, T9CC, T9CF.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 106,
    name: "Regenerowana turbosprężarka Bi-Turbo Renault Master 2.3 dCi M9T",
    brand: "Renault",
    model: "Master",
    engineCode: "",
    oemNumber: "",
    price: 2599,
    b2bPrice: 2290,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: true,
    description: "Turbosprężarka Twin Turbo dla Renault Master, Trafic, Opel Movano 2.3 dCi.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 107,
    name: "Regenerowana turbosprężarka VW Audi Skoda Seat 1.9 TDI 105KM BXE BKC",
    brand: "Audi",
    model: "1.9 TDI",
    engineCode: "",
    oemNumber: "",
    price: 699,
    b2bPrice: 620,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: false,
    description: "Turbosprężarka dla grupy VAG (Golf V, Passat B6, Octavia, Leon, A3) z silnikami 1.9 TDI 105KM (BJB, BKC, BXE). Gwarancja 24 miesiące.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 108,
    name: "Regenerowana turbosprężarka Hyundai H-1 Starex iLoad 2.5 CRDi 170KM",
    brand: "Hyundai",
    model: "Hyundai turbo",
    engineCode: "",
    oemNumber: "",
    price: 1350,
    b2bPrice: 1190,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: false,
    description: "Turbina do Hyundai H-1, Starex, i800 z silnikiem 2.5 CRDi o mocy 170KM. Kod silnika: D4CB 16V. Chłodzona cieczą.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
  {
    id: 109,
    name: "Regenerowana turbosprężarka Dacia Renault Nissan 1.2 TCe 115KM",
    brand: "Renault",
    model: "Nissan",
    engineCode: "",
    oemNumber: "",
    price: 1499,
    b2bPrice: 1320,
    warranty: "24 miesiące",
    available: true,
    isNew: false,
    isBestseller: true,
    description: "Turbina benzynowa do Renault (Clio, Captur, Megane), Dacia (Duster, Sandero) i Nissan (Qashqai, Juke) 1.2 TCe / DIG-T.",
    specs: ["Regeneracja VSR 301", "Balansowanie dynamiczne CNC", "Test ciśnienia i szczelności", "Gwarancja 24 miesiące"],
  },
];

export const categories: Category[] = [
  { name: "Audi", slug: "audi", count: 26 },
  { name: "Ford", slug: "ford", count: 18 },
  { name: "Volkswagen", slug: "volkswagen", count: 12 },
  { name: "Opel", slug: "opel", count: 10 },
  { name: "Mercedes", slug: "mercedes", count: 9 },
  { name: "Inne", slug: "inne", count: 8 },
  { name: "Hyundai", slug: "hyundai", count: 8 },
  { name: "BMW", slug: "bmw", count: 7 },
  { name: "Renault", slug: "renault", count: 6 },
  { name: "Peugeot", slug: "peugeot", count: 3 },
  { name: "Volvo", slug: "volvo", count: 2 },
];
